---
title: "sampling_locations_map"
output: html_document
---

```{r setup, message=FALSE}
library(ggmap)
library(maps)
library(tidyverse)
```

```{r load data}
loc_file <- snakemake@input[[1]]

#'data/sampling_locations.txt'
```

```{r load in map outline, input label positions}
# Load file containing the coordinates for sampling locations
sampling_loc <- read_delim(file = loc_file , delim = '\t', col_names = FALSE) %>% 
  rename(pop = X1, lat = X2, long = X3)

# Load in map from maps package
nz_map <- map_data("nz")

# Manually specify label position to make it better
lab_pos <- c(1.6, -0.8, -0.5)
```

```{r plot}
# Plot the map
ggplot() + 
  geom_polygon(data = nz_map, 
               mapping = aes(x=long, 
                             y = lat, 
                             group = group), 
               fill = NA, colour = 'black' ) + 
  coord_fixed(1.4) + 
  geom_point(data = sampling_loc, 
             mapping = aes(x = long, 
                           y = lat), 
             colour = 'red', 
             size = 3.5) +
  geom_text(data = sampling_loc, 
            mapping = aes(x = long, 
                          y = lat, 
                          label = pop), 
            hjust= lab_pos) +
  theme_classic() + 
  theme(axis.line.x.top = element_line(), 
        axis.line.y.right = element_line(), 
        panel.background = element_rect(fill = NA, 
                                        colour = "black", 
                                        size = 0.7 )) +
  labs(x = 'Longitude', 
       y = 'Latitude')

```

